config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  
  resources :categories 
  resources :products
  resources :orders, only: [:create, :show]
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  get '/dashboard', to: 'profiles#dashboard'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def dashboard
    if current_user.admin
      @unsold_products = Product.where(sold: false)
      @sold_products = Product.where(sold: true)
      @categories = Category.all
    else
      @unsold_products = current_user.products.where(sold: false)
      @sold_products = current_user.products.where(sold: true)
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_card.html.erb
<div class="card">

  <% if current_user.admin %>
    <%= link_to product_path(product[:id]) do %>
      <h3 class="card-title"><%= product.name %> (<%= product.user.name %>)</h3>
    <% end %>
  <% else %>
    <%= link_to product_path(product[:id]) do %>
      <h3 class="card-title"><%= product.name %></h3>
    <% end %>
  <% end %>
  
  <%= image_tag product.image if product.image.attached? %>
  <h5 class="card-subtitle mb-2 text-muted"><%= link_to"#{product.category.name}", category_path(product.category) %></h6>
  <p class="card-text"><%= product.short_description %></p>

  <p class="card-price"><%= product.price_display %></p>

  <section class="user-buttons">
    <%= link_to 'View', product_path(product), class: 'btn btn-primary' %>      
    <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %>                
    <%= link_to 'Delete', product, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>        
  </section>
  
</div>

app/views/profiles/_sidebar.html.erb
<div class="sidebar">
  <h3 class="side"><%= link_to "View categories", categories_path %></h3>
  <h3 class="side"><%= link_to "Add new category", new_category_path %></h3>
</div>

app/views/profiles/dashboard.html.erb
<% if current_user.admin? %>
  <%= render "sidebar" %>
<% else %>
  <%= render "shared/sidebar" %>
<% end %>

<div class="container">
  <h1>My Dashboard</h1>

  <h3>Unsold products:</h3>
  <% @unsold_products.each do |product| %> 
    <%= render 'card', product: product %>
  <% end %>

  <h3>Sold products:</h3>
  <% @sold_products.each do |product| %> 
    <%= render 'card', product: product %>
  <% end %>
</div>