config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  
  resources :categories 
  resources :products
  resources :orders, only: [:create, :show]
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  get '/dashboard', to: 'profiles#dashboard'
end

app/models/category.rb
class Category < ApplicationRecord
  # used to have 20 chars max for the name, but changed later
  validates :name, presence: true, length: { in: 2..30 }
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category ,only: [ :edit, :update, :destroy] 
  before_action :authenticate_user!, except: [:show]
  before_action :find_unsold, only: [:show]
  load_and_authorize_resource
  
  def index
    @categories = Category.all.order('name')

  end

  def show
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def find_unsold
    find_category()
    @products = @category.products.where(sold: false)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true, class: "products-form" do |form| %>

  <%= form.label :category_name %>
  <%= form.text_field :name %>

  <%= form.label :description %> 
  <%= form.text_field :description %> 

  <%= form.label :image %>
  <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<div class="content">
  <h1>Edit <%= @category.name %></h1>

  <%= render 'form' %>

  <%= link_to '☠ Cancel ☠', category_path(@category), class: 'btn btn-primary btn-cancel' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <% @categories.each do |category| %>    
    
    <div class="card">
      <h3 class="card-title"><%= link_to "#{category.name}", category_path(category) %></h3>
      
      
      <%# <%= image_tag category.image if category.image.attached? %> 
      <p class="card-text"><%= category.description %></p>
      <section class="user-buttons">
        <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-info' %>

        <% if category.products.empty? %>
          <%= link_to 'Delete', category, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
        <% end %>
      </section>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="content">
  <h1>Create new category</h1>

  <%= render "form" %>
</div>

app/views/categories/show.html.erb
<%= render 'shared/sidebar' %>

<div class="container">
  <h1><%= @category.name %></h1>
  <%# <%= image_tag @category.image if @category.image.attached? %> 
  <p class="card-text"><%= @category.description %></p>

  <% if can? :manage, :all %>
    <%= link_to 'Edit category', edit_category_path(@category), class: 'btn btn-info' %>
    <% if @products.empty? %>
      <%= link_to 'Delete category', @category, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
    <% end %>
  <% end %>

  <% @products.each do |product| %>
    <div class="card">
      <h3 class="card-title"><%= product.name %></h3>
      <%= image_tag product.image if product.image.attached? %>
      <p class="card-text"><%= product.description %></p>
      <p class="card-price"><%= product.price_display %></p>
      <section class="user-buttons">
        <%= link_to 'View', product_path(product), class: 'btn btn-primary' %>
        
        <% if can? :edit, product %>
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %>
        <% end %>

        <% if can? :destroy, product %>
          <%= link_to 'Delete', product, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
        <% end %>
      </section>
    </div>
  <% end %>
</div>