config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  
  resources :categories 
  resources :products
  resources :orders, only: [:create, :show]
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  get '/dashboard', to: 'profiles#dashboard'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { in: 2..20 }
  validates :description, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than: 0 }

  belongs_to :user
  belongs_to :category
  has_many :order_products
  has_many :orders, through: :order_products
  has_one_attached :image

  def price_display
    '$' + sprintf('%.2f', (self.price / 100.0))
  end

  def short_description
    if self.description.length > 70
      self.description[0..69] + '...'
    else
      self.description
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :find_product ,only: [:show, :edit, :update, :destroy] 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :show_sidebar, only: [:index, :show]
  before_action :find_unsold, only: [:index]
  before_action :find_similar_products ,only: [:show]
  load_and_authorize_resource
  
  def index
    num_prod = @unsold_products.length
    products_shown = 6
    
    if num_prod > products_shown 
      @products = @unsold_products.order('created_at ASC').drop(num_prod - products_shown).reverse
    else
      @products = @unsold_products.order('created_at DESC')
    end

  end

  def show
  end

  def create
    @product = current_user.products.create(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy

    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :category_id)
    # params.permit(:name, :description, :price, :image, :category_id)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def show_sidebar
    @show_sidebar = true
  end

  def find_unsold
    @unsold_products = Product.all.where(sold: false)
  end

   def find_similar_products
    similar = @product.category.products.where(sold: false) - [@product]
    if similar.any?
      if similar.length > 2
        @similar_products = similar.sample(3)
      else 
        @similar_products = similar
      end
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: @product, local: true, class: "products-form" do |form| %>
  <div>
    <%= form.label :product_name %>
    <%= form.text_field :name, maxlength: 20 %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description, maxlength: 255, size: 30 %>
  </div>

  <div>
    <%= form.label :category %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, prompt: 'Select category') %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>
  
  <%= form.submit "Aye" %>
<% end %>

app/views/products/edit.html.erb
<div class="content">
  <h1>Edit <%= @product.name %></h1>

  <%= render 'form' %>

  <%= link_to '☠ Cancel ☠', product_path(@product), class: 'btn btn-primary btn-cancel' %>
</div>

app/views/products/index.html.erb
<div class="container">
  <% @products.each do |product| %> 
    <div class="card">
      <%= image_tag product.image if product.image.attached? %>

      <h3 class="card-title"><%= product.name %></h3>
      <h5 class="card-subtitle mb-2 text-muted"><%= link_to"#{product.category.name}", category_path(product.category) %></h6>
      <p class="card-text"><%= product.short_description %></p>

      <p class="card-price"><%= product.price_display %></p>

      <section class="user-buttons">
        <%= link_to 'View', product_path(product), class: 'btn btn-primary' %>
        
        <% if can? :edit, product %>
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %>
        <% end %>

        <% if can? :destroy, product %>
          <%= link_to 'Delete', product, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
        <% end %>
      </section>
      
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="content">
  <h1>Add a new ad</h1>

  <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="container-show">
 
  <div class="show">
    <h1 class="card-title"><%= @product.name %></h1>
    <p class="card-price"><%= @product.price_display %></p>
    <div class="card-subtitle">
      <strong>Category:  </strong>
      <%= link_to Category.find(@product.category_id).name, category_path(@product.category_id) %>
    </div>

    <% if user_signed_in? && @product.user.id != current_user.id && !@product.sold %>
        <%= link_to "Add to cart", orders_path(product_id: @product), method: :post, class: 'btn cart-button' %>
    <% end %>
    
    <div class="show-image">
      <%= image_tag @product.image if @product.image.attached? %>
    </div>
    
    <p class="card-text"><%= @product.description %></p>

    <section class="show-user-buttons">      
      <% if can? :edit, @product %>
          <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-info'%>
      <% end %>

      <% if can? :destroy, @product %>
          <%= link_to 'Delete', product_path(@product), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
      <% end %>

      <%= link_to 'Back', products_path, class: 'btn btn-primary' %> 
    </section>
  </div>
    <% if @similar_products %>
      <h2>Similar products:</h2>
      <div class="similar">
        <% @similar_products.each do |product| %> 
    
          <div class="card-similar">
            <%= link_to product_path(product) do %>
              <h3 class="card-title"><%= product.name %></h3>
              <%= image_tag product.image if product.image.attached? %>
            <% end %>
            <p class="card-price"><%= product.price_display %></p>          
          </div>
        <% end %>
      <% end %>
  </div>

</div>